### ISSUE TITLE
How to mockup antd components using Jest

### ISSUE THREAD

**Issue by DavidHe1127** [ant-design/antd-demo-jest#2]
I have my own component depending on a few antd components. I wonder how to mock these components up.

Login.js
```
import { Form, Input, Icon, Button, Spin } from 'antd';

function Login() {
  return (
    <Form>....</Form>
  );
}
```

test.js
```
import React from 'react';

import { shallow, mount } from 'enzyme';
import renderer from 'react-test-renderer';

import Login from '../components/Login';
.....
.....
```
When the test is run, I get the error as follow.

```
    Cannot find module 'antd/lib/button/style/css' from 'Login.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:179:17)
      at Object.<anonymous> (components/Login.js:1:176)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.029s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```
However, I have NEVER EVER installed `antd` as my dependency and have no idea why the error still points me at `antd/lib/button/style/css`.

As thus, what is the correct way to mock up antd?

Thanks

**Comment by yesmeck** [comment]
Are you using babel-plugin-import?

**Comment by DavidHe1127** [comment]
@yesmeck 
Yup. I have figured that out already. 
I will close this ticket now.

Thanks
